version: 2

jobs:
  build:
    docker:
      - image: satellitex/python_with_protobuf
    working_directory: /iroha-python

    steps:
      - checkout
      - run:
      name: pip3 install
      command: |
        pip install -r requirements.txt
      - run:
          name: tox
          command: |
          make all
          tox
