version: 2
jobs:
  build:
    working_directory: /opt/iroha-python
    docker:
      - image: satellitex/python_with_protobuf
    steps:
      - checkout
      - run:
          name: tox
          command: |
            pip install -r requirements.txt
            make all
            tox
      - run:
          name: lint
          command: |
            pylint `find iroha -name '?*py'`
            pylint `find tests -name '?*py'`
