version: 2

jobs:
  build:
    docker:
      - image: alpine:3.5
    working_directory: /iroha-python

    steps:
      - run:
          name: Install system-wide packages
          command: apk add --no-cache --no-progress cmake curl g++ git ninja openssh python2-dev python3-dev

      - checkout

      - run:
          name: tox
          command: |
          make all
          tox
